# -*- coding: utf-8 -*-
"""NM-AI stock Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thvuHNmaIo7a48d0rqFbKhOuA19qzmQY
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()
df = pd.read_csv('NVIDIA_STOCK.csv')
df.head()

# Drop the first two header rows
df = df.drop([0, 1]).reset_index(drop=True)

# Rename columns
df.columns = ['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

# Convert to appropriate types
numeric_cols = ['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Drop missing values
df = df.dropna().reset_index(drop=True)

df.info()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_zscore = df.copy()
df_zscore[numeric_cols] = scaler.fit_transform(df_zscore[numeric_cols])

df_zscore.head()

df_encoded = df.copy()

# Extract date components
df_encoded['Year'] = df_encoded['Date'].dt.year
df_encoded['Month'] = df_encoded['Date'].dt.month
df_encoded['DayOfWeek'] = df_encoded['Date'].dt.dayofweek

# One-hot encode
df_encoded = pd.get_dummies(df_encoded, columns=['Year', 'Month', 'DayOfWeek'])

df_encoded.head()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 6))
sns.lineplot(data=df, x='Date', y='Close', label='Close Price')
sns.lineplot(data=df, x='Date', y='Open', label='Open Price')
plt.title('NVIDIA Stock Prices Over Time')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(14, 4))
sns.lineplot(data=df, x='Date', y='Volume', color='purple')
plt.title('NVIDIA Stock Volume Over Time')
plt.xlabel('Date')
plt.ylabel('Volume')
plt.grid(True)
plt.tight_layout()
plt.show()